### PR TITLE
Search!

### PR DESCRIPTION
**Pull request by smashwilson**
screen shot 2014-07-30 at 4 37 15 pm

### CODE REVIEW

**Comment by smashwilson** [comment]
Note that this will always show the _first_ result from the search. I don't know if we want to make it a random result instead.

**Comment by rgbkrk** [comment]
This won't catch when there are no results for a query too.

**Comment by smashwilson** [comment]
There we go.

**Comment by rgbkrk** [comment]
```
$ apm publish minor
Preparing and tagging a new version ✓
Pushing v0.1.0 tag ✓
Publishing giphy@v0.1.0 ✓
```

**Pull request merged**
